name: storage
description: Storage package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: 1.17.0
  meta: 1.8.0
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0
  logger: ^1.1.0
  common:
    path: ../common

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
