name: dls_one
description: DLS One
publish_to: 'none'
version: 0.23.0606+37

environment:
  sdk: ">=2.19.2 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Packages
  common:
    path: packages/common
  storage:
    path: packages/storage
  rest_api:
    path: packages/rest_api
  dls_matrix_client:
    path: packages/matrix_client
  sip_repository:
    path: packages/sip_repository
  socket_api_models:
    path: packages/socket_api_models
  notifications_models:
    path: packages/notifications_models
  dls_calendar:
    path: packages/dls_calendar
  services_watcher:
    path: packages/services_watcher

  # Dev
  logger: ^1.3.0

  # Core
  uuid: ^3.0.7
  collection: 1.17.0
  path: 1.8.2
  list_diff: ^2.0.1 # Web
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  rxdart: ^0.27.7
  mime: ^1.0.4

  # Code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Storage
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.0

  # Network
  flutter_webrtc: ^0.9.26
  connectivity_plus: any
  web_socket_client: ^0.1.0-dev.3

  # BLoC
  bloc_concurrency: ^0.2.1
  flutter_bloc: ^8.1.2

  # Navigation
  auto_route: ^6.4.0

  # Intl
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  # For E2EE, libolm must be provided.
  #Additionally, OpenSSL (libcrypto) must be provided on native platforms for E2EE.
  #For flutter apps you can easily import it with the flutter_olm and the flutter_openssl_crypto packages.
  matrix: ^0.18.3
  # flutter_olm: any
  # flutter_openssl_crypto: any

  # Firebase
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_crashlytics: ^3.3.2

  # System
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  file_picker: ^5.2.9
  gallery_saver: ^2.3.2
  open_filex: ^4.3.2
  record: ^4.4.4
  camera: ^0.10.5
  camera_web: ^0.3.1+3
  camera_macos: ^0.0.6+5
  camera_windows: ^0.2.1+6
  permission_handler: ^10.2.0 # Mobile / Desktop
  permission_handler_web: ^0.0.2 # Web
  device_info_plus: ^8.2.0
  flutter_local_notifications: ^14.1.0
  wakelock: ^0.6.2
  just_audio: ^0.9.32
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  volume_controller: ^2.0.6
  move_to_background: ^1.0.2
  flutter_dropzone: ^3.0.5
  pasteboard: ^0.2.0
  
  # UI
  flutter_native_splash: 2.2.16
  flutter_svg: 2.0.2
  extended_masked_text: ^2.3.1
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.7+3
  flutter_layout_grid: ^2.0.1
  emoji_picker_flutter: ^1.5.4
  flutter_quill: ^7.1.11
  syncfusion_flutter_datepicker: ^21.1.39
  multi_split_view: ^2.4.0
  calendar_view: ^1.0.3
  scrollable_positioned_list: ^0.3.8
  time_picker_widget: ^1.0.0+10
  graphview: ^1.2.0
  expandable_page_view: ^1.0.17
  boxy: ^2.0.9
  sliver_tools: ^0.2.10

  # Media player
  video_player: ^2.5.2 # WEB / android
  video_player_win: ^2.2.2 # windows 
  video_player_macos: ^2.0.1
  flutter_vlc_player: ^7.2.0 # iOS
  dart_vlc: ^0.4.0 # linux / MacOS in separeted PR of this plugin

  timeago: 3.3.0
  html: ^0.15.2

  flutter_screenutil: ^5.7.0

  # Remove candidates
  queen_validators: ^1.0.1
  dropdown_button2: ^1.9.4
  local_auth: ^2.1.6
  extended_image: ^7.0.2
  badges: ^2.0.3
  cross_file: ^0.3.3+4

  flutter_keyboard_visibility: ^5.4.0
  flutter_keyboard_size: ^1.0.1

dev_dependencies:
  # Code generation
  freezed: 2.2.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.6.1
  auto_route_generator: ^6.2.0

  # Analysis
  very_good_analysis: ^4.0.0+1

  # Utils
  flutter_launcher_icons: 0.11.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#3C85E8"
    theme_color: "#3C85E8"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/icons/"
    - "assets/auth/"

flutter_gen:
  output: lib/common/gen/assets
  line_length: 120
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    fonts:
      enabled: true
    output:
      style: dot-delimiter
      package_parameter_enabled: false

flutter_intl:
  enabled: true

  main_locale: ru

  arb_dir: lib/l10n

  output_dir: lib/common/gen/localization

  use_deffered_loading: false
