// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvBFKX_MRxKXtLwhEyVrft3_zmEhTt0E',
    appId: '1:46145425096:web:496be87b73a8b002e91ffd',
    messagingSenderId: '46145425096',
    projectId: 'dls-one',
    authDomain: 'dls-one.firebaseapp.com',
    storageBucket: 'dls-one.appspot.com',
    measurementId: 'G-GTX3XCY174',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC656JSkbQfyAyvV82xMaaXqtEEdhA5h-k',
    appId: '1:46145425096:android:04339933d0c29c9ce91ffd',
    messagingSenderId: '46145425096',
    projectId: 'dls-one',
    storageBucket: 'dls-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhl1DHXEN6PJkIpRYi95QQ_AAAc391WmU',
    appId: '1:46145425096:ios:cf47987f8f8a7f8de91ffd',
    messagingSenderId: '46145425096',
    projectId: 'dls-one',
    storageBucket: 'dls-one.appspot.com',
    iosClientId: '46145425096-78jjtsedtotmjhnd104lqontjqipj0ss.apps.googleusercontent.com',
    iosBundleId: 'tech.shvetsov.dlsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhl1DHXEN6PJkIpRYi95QQ_AAAc391WmU',
    appId: '1:46145425096:ios:cf47987f8f8a7f8de91ffd',
    messagingSenderId: '46145425096',
    projectId: 'dls-one',
    storageBucket: 'dls-one.appspot.com',
    iosClientId: '46145425096-78jjtsedtotmjhnd104lqontjqipj0ss.apps.googleusercontent.com',
    iosBundleId: 'tech.shvetsov.dlsChat',
  );
}
