name: sip_repository
description: SIP package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_webrtc: ^0.9.26
  sip_ua: 0.5.6
  equatable: ^2.0.5

dev_dependencies:
  very_good_analysis: ^4.0.0+1
