name: dls_matrix_client
description: Matrix chat client package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  common:
    path: ../common
  collection: 1.17.0
  # поэксперементировать с шифрованием
  # For E2EE, libolm must be provided.
  # Additionally, OpenSSL (libcrypto) must be provided on native platforms for E2EE.
  # For flutter apps you can easily import it with the flutter_olm and the flutter_openssl_crypto packages.
  # !!! Warning: Update version carefully, because higher version have a problem with synchronization
  matrix: 0.18.3
  equatable: ^2.0.5
  json_annotation: ^4.8.0

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  very_good_analysis: ^4.0.0+1
