include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/common/gen/*
    - lib/generated**
    - lib/gen**
    - lib/common/gen**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.gr.dart
    - lib/**.config.dart
    - lib/fork/**
    - audio_waveforms/**

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_relative_lib_imports: true
    avoid_function_literals_in_foreach_calls: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_relative_imports: false
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    sort_constructors_first: true
    unnecessary_const: true
    unnecessary_this: true
    use_key_in_widget_constructors: true

    no_duplicate_case_values: true
    unnecessary_statements: true

    curly_braces_in_flow_control_structures: true
    prefer_expression_function_bodies: false
    always_put_control_body_on_new_line: true

