name: notifications_models
description: Notifications models package
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  common:
    path: ../common
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  # Code generation
  json_serializable: ^6.6.1
  freezed: ^2.3.4
  build_runner: ^2.3.3

  # Analysis
  very_good_analysis: ^4.0.0+1
